### ISSUE TITLE
Videos following Tab is gone

### ISSUE THREAD

**Issue by LukasThyWalls** [crackededed/Xtra#286]
Hello.

In the "Following" section, it only shows _Games_, _Live_ and _Channels_ tabs, the _Videos_ one es missing.

In _Settings -> Default Following Tab_ is shown _Videos_ as an option, although it doesn't appear later when i open te app (it shows _Live_ tab).

Thanks.

**Comment by crackededed** [comment]
you need a gql token for this. currently you can't get one in the app because the login method used stopped working

**Comment by LukasThyWalls** [comment]
I just confirmed that in 2.17.7 is missing too (it was there before), so i changed the title.

**Comment by crackededed** [comment]
yes should be fixable

**Comment by crackededed** [comment]
fixed now. you will need to relogin

**Comment by LukasThyWalls** [comment]
I just installed 2.18.1, i tried to re-login, and later i wiped all Xtra data, and the Video tab is still missing.

The GQL Token in API settings is still empty.

**Comment by crackededed** [comment]
the fix is in 2.18.2

**Comment by LukasThyWalls** [comment]
I'm on 2.18.2 (f-droid lastest), i tried to re-login (it also asked to autorize again Xtra to access my account), and now it shows again the Video tab.

The CQL Token shows now something.

I also cleaned the cache (not wiped all app data) before login in again, i don't think it's needed but i did it anyway.

**Comment by Sytten** [comment]
Ha right I might be on the helix token only I forgot I switched it.
