### ISSUE TITLE
Message Window Is Missing

### ISSUE THREAD

**Issue by Havenos** [crackededed/Xtra#495]
On the last version of the app the message window that used to type is not appearing.

**Comment by Kojirremer** [comment]
Yes, same issue. Tried with my main and secondary accounts and the area for typing chat messages is gone. Touching messages also does not show the "Reply" option.

**Comment by Chndnngr** [comment]
> Yes, same issue. Tried with my main and secondary accounts and the area for typing chat messages is gone. Touching messages also does not show the "Reply" option.

He is not gonna listen to us man, he is busy in replying to some tor shit, why the developer will hear about some problem happening inside the app

**Comment by ubergeek77** [comment]
@Chndnngr You being disgruntled about the developer's availability is no reason to go around [closing legitimate issues](https://github.com/crackededed/Xtra/issues/486)

Can you reopen that one please? I was following it.

This is an open source repo. Anyone can investigate these issues and PR fixes at any time. Please remember that the developer is not paid to maintain this nor does he owe us any attention.

**Comment by Chndnngr** [comment]
> @Chndnngr You being disgruntled about the developer's availability is no reason to go around [closing legitimate issues](https://github.com/crackededed/Xtra/issues/486)
> 
> Can you reopen that one please? I was following it.
> 
> This is an open source repo. Anyone can investigate these issues and PR fixes at any time. Please remember that the developer is not paid to maintain this nor does he owe us any attention.

Sorry for ranting about the developer, and i had reopened the issue and i have also found and an solution for it i.e. there is a option called "don't turn off screen even after stream is finished" turn it on and vallah

**Comment by Chndnngr** [comment]
> On the last version of the app the message window that used to type is not appearing.



> Yes, same issue. Tried with my main and secondary accounts and the area for typing chat messages is gone. Touching messages also does not show the "Reply" option.



> Yes, exact same issue.
> 
> Moto Razor +, Android 13

Try using the version 2.32.0 apk, if its not available in GitHub then it will be available in fdroid, i tried using it just now and it works for me

**Comment by Havenos** [comment]
> > On the last version of the app the message window that used to type is not appearing.
> 
> > Yes, same issue. Tried with my main and secondary accounts and the area for typing chat messages is gone. Touching messages also does not show the "Reply" option.
> 
> > Yes, exact same issue.
> > Moto Razor +, Android 13
> 
> Try using the version 2.32.0 apk, if its not available in GitHub then it will be available in fdroid, i tried using it just now and it works for me

 I tried two different and its still not fixed. Android 10 Galaxy A7 (2018). I know its an old phone I just don't like upgrading phones

**Comment by crackededed** [comment]
does it work on a fresh install of latest version?

**Comment by Chndnngr** [comment]
> does it work on a fresh install of latest version?

Nope, my favourite developer

**Comment by Chndnngr** [comment]
> > > On the last version of the app the message window that used to type is not appearing.
> > 
> > 
> > > Yes, same issue. Tried with my main and secondary accounts and the area for typing chat messages is gone. Touching messages also does not show the "Reply" option.
> > 
> > 
> > > Yes, exact same issue.
> > > Moto Razor +, Android 13
> > 
> > 
> > Try using the version 2.32.0 apk, if its not available in GitHub then it will be available in fdroid, i tried using it just now and it works for me
> 
> I tried two different versions of the app and its still not fixed. Android 10 Galaxy A7 (2018). I know its an old phone I just don't like upgrading phones Edit: Seems like 2.31.3 works. All the versions of above that has the problem though.

What yo do is install the 2.31.3 then update it to 2.32.0 , i have done the same , also i had j6 A10 , and it worked for me

**Comment by d4niel-P** [comment]
I noticed that it happens (although very rarely) when the login expires. The app for some reason still shows you logged in - it shows the live channels you follow on twitch for example - but typing is impossible. You can fix it only by cleaning app's data or reinstalling it, and then logging in again.

**Comment by Chndnngr** [comment]
> I noticed that it happens (although very rarely) when the login expires. The app for some reason still shows you logged in - it shows the live channels you follow on twitch for example - but typing is impossible. You can fix it only by cleaning app's data or reinstalling it, and then logging in again.

Tried it, but nothing happens

**Comment by Havenos** [comment]
> does it work on a fresh install of latest version?

No, like I said only the 2.31.3 version work. All of the newest versions has the problem. Also I tried Android 4 version and that works too.

**Comment by SylveonBottle** [comment]
> > does it work on a fresh install of latest version?
> 
> No, like I said only the 2.31.3 version work. All of the newest versions has the problem. Also I tried Android 4 version and that works too.

Yes, this fixed it. I can choose version 2.31.3 in f-droid and chat normally again, thank you.

**Comment by E-Bosher** [comment]
Version 2.32.1.
I got logged out and after logging back in - the chat input field is gone.
It was working after each update before with no problems until the logout.

![no_chat_input_field](https://github.com/crackededed/Xtra/assets/36887996/5498beac-957c-4f49-be72-dcc9e5b7e471)

Something got messed up in that massive "VOD chat downloads" revamp after version 2.31.3.
Maybe it is a chat permission issue since it happens only after you logout?

**Comment by Havenos** [comment]
The problem is still not fixed even with newest version of the app that got released after 2 weeks I posted this.
I don't understand why even update the app while problem is still there...

**Comment by Garries420** [comment]
> does it work on a fresh install of latest version?

Newest version of Xtra (2.32.1) doesnt work, im using a samsung galaxy s22 ultra
![SmartSelect_20240610_051835_Software update](https://github.com/crackededed/Xtra/assets/162292005/616c1bcc-2d99-4049-a530-39b96d899c5f)

I miss being able to chat. Sadge.

**Comment by crackededed** [comment]
you can try putting your stuff in manually in: Settings -> Api settings -> Tokens. you need Account login and GQL token or Helix token

**Comment by Garries420** [comment]
> you can try putting your stuff in manually in: Settings -> Api settings -> Tokens. you need Account login and GQL token or Helix token

![SmartSelect_20240610_141908_Xtra](https://github.com/crackededed/Xtra/assets/162292005/b60d1e87-ea6e-4a38-b740-e1d9bd004018)

The helix and gql option is already filled in, except account login, but idk what to even put there, i tried googling but find nothing, guess ill just wait for a version where it works, or try the versions people spoke about earlier which they claim works

**Comment by Kojirremer** [comment]
> > you can try putting your stuff in manually in: Settings -> Api settings -> Tokens. you need Account login and GQL token or Helix token
> 
> ![SmartSelect_20240610_141908_Xtra](https://private-user-images.githubusercontent.com/162292005/338181297-b60d1e87-ea6e-4a38-b740-e1d9bd004018.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjQ3NDcsIm5iZiI6MTcxODAyNDQ0NywicGF0aCI6Ii8xNjIyOTIwMDUvMzM4MTgxMjk3LWI2MGQxZTg3LWVhNmUtNGEzOC1iNzQwLWUxZDliZDAwNDAxOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMzAwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzM3NjdiYmVmMDczNjMzYjZjYTczMTY4NjEyM2VlNzFhN2NkMWJlYzQ1MDhlNDljZjUyYjg2Nzg1NjY0M2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LsUSSxLEfuzHelUmbIr5NjTiKsZhq_L1PZReqdQqcjA)
> 
> The helix and gql option is already filled in, except account login, but idk what to even put there, i tried googling but find nothing, guess ill just wait for a version where it works, or try the versions people spoke about earlier which they claim works

Yes, downgrading to the version right before the bug works for me, but you will have to uninstall previous version first, so take note of the config settings you changed before doing so.

**Comment by crackededed** [comment]
Account login needs to be the user name you use to login to twitch

**Comment by Garries420** [comment]
> Account login needs to be the user name you use to login to twitch

It works LETS GOOOOOOO!!!
![SmartSelect_20240610_160433_Xtra](https://github.com/crackededed/Xtra/assets/162292005/590f3b8b-18af-4417-b69b-2e75ad9c59f9)
![SmartSelect_20240610_160409_Xtra](https://github.com/crackededed/Xtra/assets/162292005/75e07172-d0b4-4c26-90a2-1ea5441280f6)

**Comment by Havenos** [comment]
> you can try putting your stuff in manually in: Settings -> Api settings -> Tokens. you need Account login and GQL token or Helix token
Can confirm this fixed the problem. Thanks!

**Comment by Havenos** [comment]
> you can try putting your stuff in manually in: Settings -> Api settings -> Tokens. you need Account login and GQL token or Helix token

This.

**Comment by hellishvictor** [comment]
I have that issue and here is how I fixed:
Got to "Settings" > "Player", "Player buttons" > "Show chat input toogle" (one of the last options): set it to active.
Now go to a live stream and on the player there will be a keyboard icon at the right-bottom. Use it for show/hide the input box.

**Comment by hellishvictor** [comment]
Here is how I fixed it:
Got to "Settings" > "Player", "Player buttons" > "Show chat input toogle" (one of the last options): set it to active.
Now go to a live stream and on the player there will be a keyboard icon at the right-bottom. Use it for show/hide the input box.

**Comment by hellishvictor** [comment]
I had that issue and here is how I fixed:
Go to "Settings" > "Player", "Player buttons" > "Show chat input toogle" (one of the last options): set it to active.
Now go to a live stream and on the player there will be a keyboard icon at the right-bottom. Use it for show/hide the input box.

**Comment by hellishvictor** [comment]
Go to "Settings" > "Player", "Player buttons" > "Show chat input toogle" (one of the last options): set it to active.
Now go to a live stream and on the player there will be a keyboard icon at the right-bottom. Use it for show/hide the input box.
That worked for me,

**Comment by elheremes** [comment]
> Account login needs to be the user name you use to login to twitch

Worked for me, just putted my twitch username on 'Account login', restarted the app and my chat input is back :)

**Comment by successtheman** [comment]
Downgrading to 2.31.3 made the chat input window show up and then I upgraded to the latest version and it still shows. Along with the chat input window not showing I also was missing the toggle chat input option for the player menu, which showed up and works after doing three steps.

**Comment by SpasilliumNexus** [comment]
I just found out about this app, had to scour the Internet to find 2.31.3, and got it from a shady site. Installed it, chat was working.

Took note of the Helix token and GQL token values from Settings > API Settings > Tokens. The rest from 2.31.3 was the same with the latest version as of this post, 2.32.2.

Uninstalled 2.31.3, revoked the app from my Twitch account, installed 2.32.2, logged in, and went back to the tokens settings to replace the Helix token and GQL token received from 2.31.3.

Finally, I added my Twitch username to Account login since it was blank, when it was filled in automatically in 2.31.3.

Closed the app, reopened it, went to a stream, and chat input works again.

My only suggestion is not limiting the latest releases to only 3 on GitHub and F-Droid. Issues such as this is a good reason why.

**Comment by crackededed** [comment]
i think it's fixed now

**Comment by slimdan77** [comment]
Unfortunately, still bad for me. Got signed off, and when I signed back on, no message window. Uninstalled and installed each of the three available builds, and no luck. Can't find older versions to try. Sad.

**Comment by crackededed** [comment]
it's fixed in 2.32.4. you can just put the login in settings manually if you're using the f-droid build. older versions can be downloaded from github actions tab

**Comment by slimdan77** [comment]
> it's fixed in 2.32.4. you can just put the login in settings manually if you're using the f-droid build. older versions can be downloaded from github actions tab

Thanks for the quick response. I can only access 2.32.3 in f-droid or github which appears to still have the problem for me. I will await 2.32.4. Thanks for all your hard work. This app is great.
