### ISSUE TITLE
[Bug] In-app PIP shows wrong aspect ratio

### ISSUE THREAD

**Issue by Oleepre** [crackededed/Xtra#801]
**App Version:** 2.51.2

**Describe the Bug**
 When opening a stream or VOD and immediately hitting the back button, the Picture-in-picture window displayed has a weird aspect ratio showing part of the chat and it covers part of the UI. Sometimes it stays at the bottom as a long strip or in the center of the screen.
 Going go the home screen and back also shows half of the player.
 The previous version of the app didn't seem to have this problem.

 **To Reproduce**
 Click on a currently live stream or VOD. Quickly hit the back button before the stream and chat cover the whole screen. Notice how it wrongly renders the PIP in the app.
 Once this happens, if you keep it in PIP without opening it in fullscreen, if you hit the Home button on your phone and then Close the PIP window in there you will see Half of the player when opening the app again.

 
https://github.com/user-attachments/assets/ec625b60-b96e-4ef3-84c4-14dc27ca6d75

![Image](https://github.com/user-attachments/assets/ae397443-f57a-4ae6-8bbb-66838605872a)

**Comment by Oleepre** [comment]
Another thing i noticed, this one is easy to reproduce. 
 Make sure picture-in-picture is On in Settings.
  - Open a Stream or VOD.
  - Press the phone's home button to go back to the homescreen.
  - With the video playing in PIP, Lock the phone.
  - Unlock it.
  - Notice the PIP windows is showing the chat instead of the video.

**Comment by crackededed** [comment]
the issue with player width and height should be fixed now

**Comment by Oleepre** [comment]
Indeed the original bug seems to be fixed, thank you. Since they're unrelated, I will open a different report for the other one which is still present.
